# Generated by Django 2.2 on 2021-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_products',
            name='Cpr_sort',
        ),
        migrations.RemoveField(
            model_name='category_products',
            name='Cpr_type',
        ),
        migrations.AddField(
            model_name='category_products',
            name='Cpr_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_name',
            field=models.TextField(max_length=255),
        ),
    ]
