# Generated by Django 2.2 on 2021-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210906_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_products',
            name='Cpr_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pr_cart_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_coupon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_pr_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category_products',
            name='Cpr_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Fb_content',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Fb_description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Fb_title',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Fb_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Od_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Od_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Od_transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreateAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pr_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pr_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pr_description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pr_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pr_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_address',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_date_buy',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_email',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Tst_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_address',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='U_phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
