# Generated by Django 2.2 on 2021-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210906_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pr_image',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
