# Generated by Django 2.2 on 2021-09-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_pr_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pr_category_products_id',
            new_name='Pr_category',
        ),
    ]
