# Generated by Django 2.2 on 2021-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210909_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pr_price_sale',
            field=models.BooleanField(default=True),
        ),
    ]
