# Generated by Django 2.2 on 2021-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_pr_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pr_price_sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pr_sale',
            field=models.BooleanField(default=True),
        ),
    ]
